name: CICD_project
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 192.168.1.51

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        
      - name: Copy code on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_PROD }} rm -rf * /var/www/html/ && cp -r ./* /var/www/html && syatemctl restart nginx
